### ISSUE TITLE
Get All Dealers not working

### ISSUE THREAD

**Issue by aqidd** [whitehorse0/simple-crud-vue-laravel#1]
Steps to reproduce

1. download / clone repo

1.  go to `server_labs`

1. rename .env.example to .env

1. change DB credentials

1. run `composer install` && `php artisan migrate` && `php artisan key:generate` && `php artisan serve`

1.  go to `client_labs_vue`

1.  run `npm install` && `npm run dev`

1.  try to create new dealer : `success` ( no feedback / response message whatsoever )

1.  try to get all dealers : nothing happened ( no feedback, no errors, upon inspecting network requests, response is successful but apparently table is not being updated )

cc @krisanalfa

**Comment by krisanalfa** [comment]
Confirmed. This is stopper bug.
